development:
  dialect: "mysql"
  database: "doitb1gdb"
  host: "doitbig.c3lglnwntifb.us-east-1.rds.amazonaws.com"
  port: "3306"
  user: "sqladmin"
  password: "asdfghjkl;'"
  encoding: "utf8mb4_general_ci"

test:
  dialect: "mysql"
  database: "doitb1gdb"
  host: "doitbig.c3lglnwntifb.us-east-1.rds.amazonaws.com"
  port: "3306"
  user: "sqladmin"
  password: "asdfghjkl;'"
  encoding: "utf8mb4_general_ci"

# production:
#   url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/doitbig-ms_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
