development:
  dialect: "mysql"
  database: "doitb1g"
  host: "mysql-doitb1gsts.cf3iw62vybyo.us-east-2.rds.amazonaws.com"
  port: "3306"
  user: "mysqladmin"
  password: "asdfghjkl;'"
  encoding: "utf8mb4_general_ci"

test:
  url: {{envOr "TEST_DATABASE_URL" "mysql://mysqladmin:asdfghjkl;'@(mysql-doitb1gsts.cf3iw62vybyo.us-east-2.rds.amazonaws.com:3306)/doitbig-ms_test?parseTime=true&multiStatements=true&readTimeout=1s"}}

production:
  url: {{envOr "DATABASE_URL" "mysql://mysqladmin:asdfghjkl;'@(mysql-doitb1gsts.cf3iw62vybyo.us-east-2.rds.amazonaws.com:3306)/doitbig-ms_production?parseTime=true&multiStatements=true&readTimeout=1s"}}
