development:
  dialect: "mysql"
  database: "doitb1g"
  host: "doitb1g-db.mysql.database.azure.com"
  port: "3306"
  user: "mysqladmin@doitb1g-db"
  password: "doitb1gasdfghjkl;'"
  encoding: "utf8mb4_general_ci"

test:
  dialect: "mysql"
  database: "doitb1g"
  host: "doitb1g-db.mysql.database.azure.com"
  port: "3306"
  user: "mysqladmin@doitb1g-db"
  password: "doitb1gasdfghjkl;'"
  encoding: "utf8mb4_general_ci"

# production:
#   url: {{envOr "DATABASE_URL" "mysql://root:root@(localhost:3306)/doitbig-ms_production?parseTime=true&multiStatements=true&readTimeout=1s"}}

