// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c7735ecf-a458-4a44-b7b8-9c21c0d9a1ea",
    "aws_cognito_region": "us-east-1",
    "aws_mobile_analytics_app_id": "afdbf6f8c39f499ca44c53a3b3a2c998",
    "aws_mobile_analytics_app_region": "us-east-1"
};


export default awsmobile;
